### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by dexdeadly** [elad-bar/shinobi-deepstack-face#1]
I just installed this on my shinobi VM.  I'd like to have this work within Home Assistant so that I can trigger things based off my face and time if possible.  After running the commands in readme I believe I was able to get it up and running.  However I noticed the following when running pm2 logs --lines 100. 

`/root/.pm2/logs/shinobi-deepstack-face-error.log last 100 lines:
2|shinobi- | Error: ENOENT: no such file or directory, open '/home/Shinobi/plugins/deepstack-face/plugins/deepstack-face/CLEANUP.sh'
`
Not sure why its doubled the plugins/deepstack-face part.  Also know that the CLEANUP.sh file doesn't exist at all.  Am I going about this all wrong?

**Comment by dexdeadly** [comment]
Another thing is I noticed in the readme your paths say /home/Shinobi/plugin and not plugins.  This gave a different error until I corrected it.   It was looking for a file found in plugins directory.

**Comment by elad-bar** [comment]
Will correct it, thanks

**Comment by jth62** [comment]
hello and thank you for this plugin, it looks great!
I followed the tutorial but I have a problem when starting,
the message is:

DeepStack-Object Plugin start has failed. pluginBase.js was not found.

here is a screenshot of my log file :
![deep](https://user-images.githubusercontent.com/46516849/156833524-a260abe4-9ebb-421f-baa6-85cb48568caf.png)

Can you help me please?
Thanks very much

**Comment by elad-bar** [comment]
repository moved to gitlab, please read the readme.md
